---
title: "Convert-data-for-exp1"
author: "Josh White"
date: "18/02/2021"
output: html_document
---

```{r setup,}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```

## Import, clean and save data to put online. 

```{r import-data, warning = FALSE}
d <- read_csv("parsedrawresults.csv", col_types = "ifffffnnfnfc")
d <- d %>%
  select(-X1)

glimpse(d)

#### change vignette numbers for ease of reading in paper ####

d <- d %>%
  select(-condition) %>% #remove old condition variables
  mutate(
    
    #create new variable for vignette type + number
    vignette = paste0(vignetteType, vignetteNumber) %>% factor(), 
    
    # Change numbering of vignettes for easier understanding ###
    vignette = recode_factor(vignette,
                G1 = 'G5', G2 = 'G6', G3 = 'G3', G4 = 'G8', G5 = 'G9', G6 = 'G10',
                G7 = 'G7', G8 = 'G2', G9 = 'G4', G10 = 'G1', G11 = 'G11', G12 = 'G12',
                L1 = 'L5', L2 = 'L8', L3 = 'L7', L4 = 'L9', L5 = 'L10', L6 = 'L2',
                L7 = 'L1', L8 = 'L11', L9 = 'L12', L10 = 'L6', L11 = 'L4', L12 = 'L3'),
    
    #reset order from G1 to L12 for easy graphing
    vignette = factor(vignette, levels = c(sprintf("G%d", seq(1:12)), sprintf("L%d", seq(1:12))))
  )

# now change vignetteNumber column too so it matches up with these changes. 
# gain vignettes first 
d$vignetteNumber[d$vignetteType == "G"] <- 
  d$vignetteNumber[d$vignetteType == "G"] %>% 
  recode_factor(`1` = '5', `2` = '6', `3` = '3', `4` = '8', `5` = '9', `6` = '10',
                `7` = '7', `8` = '2', `9` = '4', `10` = '1', `11` = '11', `12` = '12')

#now losses
# gain vignettes first 
d$vignetteNumber[d$vignetteType == "L"] <- 
  d$vignetteNumber[d$vignetteType == "L"] %>% 
  recode_factor(`1` = '5', `2` = '8', `3` = '7', `4` = '9', `5` = '10', `6` = '2',
                `7` = '1', `8` = '11', `9` = '12', `10` = '6', `11` = '4', `12` = '3')

#redo condition variable to take all these changes into account
d$condition <- paste0(d$vignetteType, d$vignetteNumber, d$answerOrder) %>% factor()

#finally change names of postquestion variables to postQuestion
d <- d %>%
  rename(
    postQuestion1 = postquestion1,
    postQuestion2 = postquestion2
  )

#reorder data frame
d <- d[, c(1, 12, 2:4, 11, 5:10)]

glimpse(d)

#save datset to put up on osf
write_csv(d, "exp1data.csv")

```